Added bootstrap classes to left bar
KamandPrompt/baat-cheet pull request #96
Opened 2020-10-06 12:01 UTC by Aditya-ds-1806

fixes #92

2020-10-06 12:08 UTC, Aditya-ds-1806 commented
hey, as requested i have styled the input, toggle button. So now the whole left bar is styled with bootstrap classes

2020-10-06 16:04 UTC, LalitNM commented
Not accetpable @Aditya-ds-1806. There were a lot more discussion in #93. Add all those changes.

2020-10-06 16:07 UTC, Aditya-ds-1806 commented
Can you please elaborate? The requirement was to style the left bar with bootstrap classes and I did that.

2020-10-06 16:08 UTC, Aditya-ds-1806 commented
In the discussion, i was asked to style the input and the toggle button, which I did

2020-10-06 17:31 UTC, LalitNM commented
I don't think that I have to explain it again, everything is well elaborated there in #93.

Still because you have asked me to elaborate...
`<input>` tag should be like any normal bootstrap's input form, see screenshot=>
![image](https://user-images.githubusercontent.com/63332774/95238639-4e7d0780-07f9-11eb-961b-eba88ad6f610.png)

and the toggle collapse button should be like any bootstrap button, read about bootstrap buttons, and for the division of room name you have to be creative, think about it.

2020-10-06 21:19 UTC, Aditya-ds-1806 commented
All right, now I understand. Will finish it in half an hour. Thanks!

2020-10-06 21:40 UTC, Aditya-ds-1806 commented
![image](https://user-images.githubusercontent.com/46485997/95262442-c1ae6a00-0849-11eb-96d2-ec0d61037f27.png)
![image](https://user-images.githubusercontent.com/46485997/95262865-8ceee280-084a-11eb-8c4f-2a5682e4b217.png)

This is the result after the recent commit. Is this fine? This is same as bootstrap default.

2020-10-07 04:33 UTC, LalitNM requested changes
In addition to the changes requested, there is a bug created by your last commit. Now the search feature of room is not working properly, earlier the search was filtering the name of rooms and showing only the name relevant to search, now it is not filtering the name of rooms.

2020-10-07 04:33 UTC, LalitNM commented on views/index.ejs
> +        <button class="btn btn-danger sidebar-btn" onclick="SidebarToggle()">
Do not add `danger` here use `primary`

2020-10-07 05:22 UTC, Aditya-ds-1806 commented
Can you check now? I fixed the errors and changed the button to primary

2020-10-07 07:03 UTC, LalitNM approved these changes

2020-10-07 07:03 UTC, LalitNM commented
Good work @Aditya-ds-1806. Merging this :rocket:

2020-10-07 07:05 UTC, merged

2020-10-07 07:10 UTC, Aditya-ds-1806 commented
Great, thanks!